using System;
using System.Collections.Generic;
using System.IO;
using Smart.Editors;
using UnityEditor;
using UnityEngine;

namespace Smart.Extensions
{
    public class eBuiltInIcons : EditorWindow
    {
        [MenuItem("Tools/Smart/Built-in Icons #&B", false, 4009)]
        private static void MainMenuItem()
        {
            Execute(null);
        }

        private static eBuiltInIcons _window;

        public static void Execute(Action<string> onSelect)
        {
            if (_window) { _window.Close(); return; }

            _window = GetWindow<eBuiltInIcons>(false, "Built-in Icons");
            _window._onSelect = onSelect;
            _window.minSize = new Vector2(300, 300);
            _window.titleContent.image = eIcons.Get("icons/d_sceneviewfx.png");
            _window.titleContent.text = "Built-in Icons";
            _window.Show();
            _window.Focus();
        }

        private Action<string> _onSelect;
        private Vector2 _scrollPosition;
        private static readonly List<string> _pathList = new List<string>();
        private string _searchText;
        private int _searchSizeMin;
        private int _searchSizeMax;

        void OnGUI()
        {
            if (_pathList.Count == 0) FillIconLists();
            eGUI.RememberColors();

            GUILayout.BeginHorizontal();
            {
                eGUI.TextEditor(ref _searchText, "Search");
                GUILayout.Label("Min", GUILayout.ExpandWidth(false));
                eGUI.IntEditor(ref _searchSizeMin, null, 35);
                GUILayout.Label("Max", GUILayout.ExpandWidth(false));
                eGUI.IntEditor(ref _searchSizeMax, null, 35);
                if (eGUI.ButtonMini(eIcons.Get("d_winbtn_win_close"), "Clear", eGUI.redLt, 18))
                {
                    _searchText = "";
                    _searchSizeMin = 0;
                    _searchSizeMax = 0;
                }
            }
            GUILayout.EndHorizontal();

            var search = string.IsNullOrEmpty(_searchText) ? null : _searchText.ToLower();
            _scrollPosition = GUILayout.BeginScrollView(_scrollPosition, false, false);
            {
                foreach (var path in _pathList)
                {
                    if (string.IsNullOrEmpty(path)) continue;
                    if ((search != null) && !path.Contains(search)) continue;

                    var tex = eIcons.Get(path);
                    if (tex == null) continue;
                    if (_searchSizeMax > 0 && (tex.width > _searchSizeMax || tex.height > _searchSizeMax)) continue;
                    if (_searchSizeMin > 0 && (tex.width < _searchSizeMin || tex.height < _searchSizeMin)) continue;

                    EditorGUILayout.BeginHorizontal();
                    {
                        DrawItem(tex, path);
                    }
                    EditorGUILayout.EndHorizontal();
                }
                GUILayout.EndScrollView();
            }
        }

        private void DrawItem(Texture2D tex, string path)
        {
            eGUI.ResetFG();
            if (GUILayout.Button(tex, GUILayout.Width(50), GUILayout.Height(32)))
            {
                if (_onSelect == null)
                {
                    EditorGUIUtility.systemCopyBuffer = path;
                    if (Event.current.control) // save texture to file
                    {
                        // save 16x16 mipmap if shift pressed
                        var w = Event.current.shift ? 16 : tex.width;
                        var h = Event.current.shift ? 16 : tex.height;
                        var rt = new RenderTexture(w, h, 32);
                        var nt = new Texture2D(w, h, TextureFormat.ARGB32, false);
                        Graphics.Blit(tex, rt);
                        RenderTexture.active = rt;
                        nt.ReadPixels(new Rect(0, 0, w, h), 0, 0);
                        RenderTexture.active = null;

                        var pngBytes = nt.EncodeToPNG();
                        try
                        {
                            File.WriteAllBytes(@"C:\UnityBuiltInIcon.png", pngBytes);
                        }
                        catch
                        {
                            File.WriteAllBytes(@"C:\1\UnityBuiltInIcon.png", pngBytes);
                        }                        
                    }
                }
                else
                {
                    _onSelect(path);
                    _onSelect = null;
                    Close();
                }
            }
            EditorGUILayout.BeginVertical();
            {
                eGUI.SetColor(eGUI.orangeLt);
                EditorGUILayout.LabelField(path.Replace("icons/", ""));
                eGUI.SetColor(eGUI.grayLt);
                EditorGUILayout.LabelField(tex.width + "x" + tex.height);
                eGUI.ResetColors();
            }
            EditorGUILayout.EndVertical();
        }

        private static void BuildIconLists()
        {
            byte[] buff;
            using (var fs = new FileStream(@"c:\Program Files\Unity\Editor\Data\Resources\unity editor resources", FileMode.Open))
            {
                buff = new byte[fs.Length];
                fs.Read(buff, 0, (int) fs.Length);
            }

            var i = 0;
            using (var sw = new StreamWriter(@"C:\1.txt"))
                while (i < buff.Length)
                {
                    if (buff[i++] != 'i') continue;
                    if (buff[i++] != 'c') continue;
                    if (buff[i++] != 'o') continue;
                    EditorUtility.DisplayProgressBar("Processing", "Scanning buffer", (float) i / buff.Length);
                    if (buff[i++] != 'n') continue;
                    if (buff[i++] != 's') continue;
                    if (buff[i++] != '/') continue;

                    var str = "";
                    while (i < buff.Length)
                    {
                        if (str.Length > 200)
                        {
                            Debug.Log("Over: " + str);
                            break;
                        }
                        str += (char) buff[i++];
                        if (str.EndsWith(".png") || str.EndsWith(".asset"))
                        {
                            _pathList.Add("icons/" + str);
                            sw.WriteLine("\t_pathList.Add(\"icons/" + str + "\");");
                            break;
                        }
                    }
                }

            EditorUtility.ClearProgressBar();
        }

        private static void FillIconLists()
        {
            //BuildIconLists();

            _pathList.Add("icons/_help.png");
            _pathList.Add("icons/_popup.png");
            _pathList.Add("icons/aboutwindow.mainheader.png");
            _pathList.Add("icons/ageialogo.png");
            _pathList.Add("icons/alphabeticalsorting.png");
            _pathList.Add("icons/animation.addevent.png");
            _pathList.Add("icons/animation.addkeyframe.png");
            _pathList.Add("icons/animation.eventmarker.png");
            _pathList.Add("icons/animation.firstkey.png");
            _pathList.Add("icons/animation.lastkey.png");
            _pathList.Add("icons/animation.nextkey.png");
            _pathList.Add("icons/animation.play.png");
            _pathList.Add("icons/animation.prevkey.png");
            _pathList.Add("icons/animation.record.png");
            _pathList.Add("icons/animation.sequencerlink.png");
            _pathList.Add("icons/animationanimated.png");
            _pathList.Add("icons/animationdopesheetkeyframe.png");
            _pathList.Add("icons/animationkeyframe.png");
            _pathList.Add("icons/animationnocurve.png");
            _pathList.Add("icons/animationvisibilitytoggleoff.png");
            _pathList.Add("icons/animationvisibilitytoggleon.png");
            _pathList.Add("icons/animationwrapmodemenu.png");
            _pathList.Add("icons/as badge delete.png");
            _pathList.Add("icons/as badge move.png");
            _pathList.Add("icons/as badge new.png");
            _pathList.Add("icons/asset store.png");
            _pathList.Add("icons/assetserver.delete.png");
            _pathList.Add("icons/audio mixer.png");
            _pathList.Add("icons/avatarcompass.png");
            _pathList.Add("icons/avatarcontroller.layer.png");
            _pathList.Add("icons/avatarcontroller.layerhover.png");
            _pathList.Add("icons/avatarcontroller.layerselected.png");
            _pathList.Add("icons/avatarinspector/bodypartpicker.png");
            _pathList.Add("icons/avatarinspector/bodysilhouette.png");
            _pathList.Add("icons/avatarinspector/dotfill.png");
            _pathList.Add("icons/avatarinspector/dotframe.png");
            _pathList.Add("icons/avatarinspector/dotframedotted.png");
            _pathList.Add("icons/avatarinspector/dotselection.png");
            _pathList.Add("icons/avatarinspector/head.png");
            _pathList.Add("icons/avatarinspector/headik.png");
            _pathList.Add("icons/avatarinspector/headzoom.png");
            _pathList.Add("icons/avatarinspector/headzoomsilhouette.png");
            _pathList.Add("icons/avatarinspector/leftarm.png");
            _pathList.Add("icons/avatarinspector/leftfeetik.png");
            _pathList.Add("icons/avatarinspector/leftfingers.png");
            _pathList.Add("icons/avatarinspector/leftfingersik.png");
            _pathList.Add("icons/avatarinspector/lefthandzoom.png");
            _pathList.Add("icons/avatarinspector/lefthandzoomsilhouette.png");
            _pathList.Add("icons/avatarinspector/leftleg.png");
            _pathList.Add("icons/avatarinspector/maskeditor_root.png");
            _pathList.Add("icons/avatarinspector/rightarm.png");
            _pathList.Add("icons/avatarinspector/rightfeetik.png");
            _pathList.Add("icons/avatarinspector/rightfingers.png");
            _pathList.Add("icons/avatarinspector/rightfingersik.png");
            _pathList.Add("icons/avatarinspector/righthandzoom.png");
            _pathList.Add("icons/avatarinspector/righthandzoomsilhouette.png");
            _pathList.Add("icons/avatarinspector/rightleg.png");
            _pathList.Add("icons/avatarinspector/torso.png");
            _pathList.Add("icons/avatarpivot.png");
            _pathList.Add("icons/beginbutton-on.png");
            _pathList.Add("icons/beginbutton.png");
            _pathList.Add("icons/blendkey.png");
            _pathList.Add("icons/blendkeyoverlay.png");
            _pathList.Add("icons/blendkeyselected.png");
            _pathList.Add("icons/blendsampler.png");
            _pathList.Add("icons/bluegroove.png");
            _pathList.Add("icons/buildsettings.android.png");
            _pathList.Add("icons/buildsettings.android.small.png");
            _pathList.Add("icons/buildsettings.blackberry.png");
            _pathList.Add("icons/buildsettings.blackberry.small.png");
            _pathList.Add("icons/buildsettings.broadcom.png");
            _pathList.Add("icons/buildsettings.editor.png");
            _pathList.Add("icons/buildsettings.editor.small.png");
            _pathList.Add("icons/buildsettings.facebook.png");
            _pathList.Add("icons/buildsettings.facebook.small.png");
            _pathList.Add("icons/buildsettings.flashplayer.png");
            _pathList.Add("icons/buildsettings.flashplayer.small.png");
            _pathList.Add("icons/buildsettings.iphone.png");
            _pathList.Add("icons/buildsettings.iphone.small.png");
            _pathList.Add("icons/buildsettings.metro.png");
            _pathList.Add("icons/buildsettings.metro.small.png");
            _pathList.Add("icons/buildsettings.n3ds.png");
            _pathList.Add("icons/buildsettings.n3ds.small.png");
            _pathList.Add("icons/buildsettings.ps4.png");
            _pathList.Add("icons/buildsettings.ps4.small.png");
            _pathList.Add("icons/buildsettings.psm.png");
            _pathList.Add("icons/buildsettings.psm.small.png");
            _pathList.Add("icons/buildsettings.psp2.png");
            _pathList.Add("icons/buildsettings.psp2.small.png");
            _pathList.Add("icons/buildsettings.samsungtv.png");
            _pathList.Add("icons/buildsettings.samsungtv.small.png");
            _pathList.Add("icons/buildsettings.selectedicon.png");
            _pathList.Add("icons/buildsettings.standalone.png");
            _pathList.Add("icons/buildsettings.standalone.small.png");
            _pathList.Add("icons/buildsettings.standalonebroadcom.small.png");
            _pathList.Add("icons/buildsettings.standalonegles20emu.small.png");
            _pathList.Add("icons/buildsettings.standaloneglesemu.png");
            _pathList.Add("icons/buildsettings.standaloneglesemu.small.png");
            _pathList.Add("icons/buildsettings.switch.png");
            _pathList.Add("icons/buildsettings.switch.small.png");
            _pathList.Add("icons/buildsettings.tizen.png");
            _pathList.Add("icons/buildsettings.tizen.small.png");
            _pathList.Add("icons/buildsettings.tvos.png");
            _pathList.Add("icons/buildsettings.tvos.small.png");
            _pathList.Add("icons/buildsettings.web.png");
            _pathList.Add("icons/buildsettings.web.small.png");
            _pathList.Add("icons/buildsettings.webgl.png");
            _pathList.Add("icons/buildsettings.webgl.small.png");
            _pathList.Add("icons/buildsettings.wiiu.png");
            _pathList.Add("icons/buildsettings.wiiu.small.png");
            _pathList.Add("icons/buildsettings.wp8.png");
            _pathList.Add("icons/buildsettings.wp8.small.png");
            _pathList.Add("icons/buildsettings.xbox360.png");
            _pathList.Add("icons/buildsettings.xbox360.small.png");
            _pathList.Add("icons/buildsettings.xboxone.png");
            _pathList.Add("icons/buildsettings.xboxone.small.png");
            _pathList.Add("icons/camera gizmo.png");
            _pathList.Add("icons/checkerfloor.png");
            _pathList.Add("icons/clipboard.png");
            _pathList.Add("icons/clothinspector.painttool.png");
            _pathList.Add("icons/clothinspector.paintvalue.png");
            _pathList.Add("icons/clothinspector.selecttool.png");
            _pathList.Add("icons/clothinspector.settingstool.png");
            _pathList.Add("icons/clothinspector.viewvalue.png");
            _pathList.Add("icons/cloudconnect.png");
            _pathList.Add("icons/collab.png");
            _pathList.Add("icons/collabconflict.png");
            _pathList.Add("icons/collaberror.png");
            _pathList.Add("icons/collabnew.png");
            _pathList.Add("icons/collaboffline.png");
            _pathList.Add("icons/collabprogress.png");
            _pathList.Add("icons/collabpull.png");
            _pathList.Add("icons/collabpush.png");
            _pathList.Add("icons/colorpicker.colorcycle.png");
            _pathList.Add("icons/colorpicker.cyclecolor.png");
            _pathList.Add("icons/colorpicker.cycleslider.png");
            _pathList.Add("icons/colorpicker.slidercycle.png");
            _pathList.Add("icons/console.erroricon.inactive.sml.png");
            _pathList.Add("icons/console.erroricon.png");
            _pathList.Add("icons/console.erroricon.sml.png");
            _pathList.Add("icons/console.infoicon.png");
            _pathList.Add("icons/console.infoicon.sml.png");
            _pathList.Add("icons/console.warnicon.inactive.sml.png");
            _pathList.Add("icons/console.warnicon.png");
            _pathList.Add("icons/console.warnicon.sml.png");
            _pathList.Add("icons/curvekeyframe.png");
            _pathList.Add("icons/curvekeyframeselected.png");
            _pathList.Add("icons/curvekeyframeselectedoverlay.png");
            _pathList.Add("icons/curvekeyframesemiselectedoverlay.png");
            _pathList.Add("icons/customsorting.png");
            _pathList.Add("icons/d__popup.png");
            _pathList.Add("icons/d_aboutwindow.mainheader.png");
            _pathList.Add("icons/d_ageialogo.png");
            _pathList.Add("icons/d_alphabeticalsorting.png");
            _pathList.Add("icons/d_animation.addevent.png");
            _pathList.Add("icons/d_animation.addkeyframe.png");
            _pathList.Add("icons/d_animation.eventmarker.png");
            _pathList.Add("icons/d_animation.firstkey.png");
            _pathList.Add("icons/d_animation.lastkey.png");
            _pathList.Add("icons/d_animation.nextkey.png");
            _pathList.Add("icons/d_animation.play.png");
            _pathList.Add("icons/d_animation.prevkey.png");
            _pathList.Add("icons/d_animation.record.png");
            _pathList.Add("icons/d_animation.sequencerlink.png");
            _pathList.Add("icons/d_animationanimated.png");
            _pathList.Add("icons/d_animationkeyframe.png");
            _pathList.Add("icons/d_animationnocurve.png");
            _pathList.Add("icons/d_animationvisibilitytoggleoff.png");
            _pathList.Add("icons/d_animationvisibilitytoggleon.png");
            _pathList.Add("icons/d_animationwrapmodemenu.png");
            _pathList.Add("icons/d_as badge delete.png");
            _pathList.Add("icons/d_as badge move.png");
            _pathList.Add("icons/d_as badge new.png");
            _pathList.Add("icons/d_asset store.png");
            _pathList.Add("icons/d_assetserver.delete.png");
            _pathList.Add("icons/d_audio mixer.png");
            _pathList.Add("icons/d_avatarblendbackground.png");
            _pathList.Add("icons/d_avatarblendleft.png");
            _pathList.Add("icons/d_avatarblendlefta.png");
            _pathList.Add("icons/d_avatarblendright.png");
            _pathList.Add("icons/d_avatarblendrighta.png");
            _pathList.Add("icons/d_avatarcompass.png");
            _pathList.Add("icons/d_avatarpivot.png");
            _pathList.Add("icons/d_beginbutton-on.png");
            _pathList.Add("icons/d_beginbutton.png");
            _pathList.Add("icons/d_bluegroove.png");
            _pathList.Add("icons/d_buildsettings.android.png");
            _pathList.Add("icons/d_buildsettings.android.small.png");
            _pathList.Add("icons/d_buildsettings.broadcom.png");
            _pathList.Add("icons/d_buildsettings.flashplayer.png");
            _pathList.Add("icons/d_buildsettings.flashplayer.small.png");
            _pathList.Add("icons/d_buildsettings.iphone.png");
            _pathList.Add("icons/d_buildsettings.iphone.small.png");
            _pathList.Add("icons/d_buildsettings.ps4.png");
            _pathList.Add("icons/d_buildsettings.ps4.small.png");
            _pathList.Add("icons/d_buildsettings.psp2.png");
            _pathList.Add("icons/d_buildsettings.psp2.small.png");
            _pathList.Add("icons/d_buildsettings.selectedicon.png");
            _pathList.Add("icons/d_buildsettings.standalone.png");
            _pathList.Add("icons/d_buildsettings.standalone.small.png");
            _pathList.Add("icons/d_buildsettings.tizen.png");
            _pathList.Add("icons/d_buildsettings.tizen.small.png");
            _pathList.Add("icons/d_buildsettings.tvos.png");
            _pathList.Add("icons/d_buildsettings.tvos.small.png");
            _pathList.Add("icons/d_buildsettings.web.png");
            _pathList.Add("icons/d_buildsettings.web.small.png");
            _pathList.Add("icons/d_buildsettings.webgl.png");
            _pathList.Add("icons/d_buildsettings.webgl.small.png");
            _pathList.Add("icons/d_buildsettings.xbox360.png");
            _pathList.Add("icons/d_buildsettings.xbox360.small.png");
            _pathList.Add("icons/d_buildsettings.xboxone.png");
            _pathList.Add("icons/d_buildsettings.xboxone.small.png");
            _pathList.Add("icons/d_checkerfloor.png");
            _pathList.Add("icons/d_cloudconnect.png");
            _pathList.Add("icons/d_colorpicker.cyclecolor.png");
            _pathList.Add("icons/d_colorpicker.cycleslider.png");
            _pathList.Add("icons/d_console.erroricon.png");
            _pathList.Add("icons/d_console.erroricon.sml.png");
            _pathList.Add("icons/d_console.infoicon.png");
            _pathList.Add("icons/d_console.infoicon.sml.png");
            _pathList.Add("icons/d_console.warnicon.png");
            _pathList.Add("icons/d_console.warnicon.sml.png");
            _pathList.Add("icons/d_curvekeyframe.png");
            _pathList.Add("icons/d_curvekeyframeselected.png");
            _pathList.Add("icons/d_curvekeyframeselectedoverlay.png");
            _pathList.Add("icons/d_curvekeyframesemiselectedoverlay.png");
            _pathList.Add("icons/d_customsorting.png");
            _pathList.Add("icons/d_defaultsorting.png");
            _pathList.Add("icons/d_editcollider.png");
            _pathList.Add("icons/d_editicon.sml.png");
            _pathList.Add("icons/d_endbutton-on.png");
            _pathList.Add("icons/d_endbutton.png");
            _pathList.Add("icons/d_eyedropper.large.png");
            _pathList.Add("icons/d_eyedropper.sml.png");
            _pathList.Add("icons/d_favorite.png");
            _pathList.Add("icons/d_filterbylabel.png");
            _pathList.Add("icons/d_filterbytype.png");
            _pathList.Add("icons/d_gear.png");
            _pathList.Add("icons/d_groove.png");
            _pathList.Add("icons/d_horizontalsplit.png");
            _pathList.Add("icons/d_icon dropdown.png");
            _pathList.Add("icons/d_in-addcomponentleft.png");
            _pathList.Add("icons/d_in-addcomponentright.png");
            _pathList.Add("icons/d_inspectorlock.png");
            _pathList.Add("icons/d_leftbracket.png");
            _pathList.Add("icons/d_lighting.png");
            _pathList.Add("icons/d_lightmapeditor.windowtitle.png");
            _pathList.Add("icons/d_lookdevcenterlight.png");
            _pathList.Add("icons/d_lookdevcenterlight@2x.png");
            _pathList.Add("icons/d_lookdevclose.png");
            _pathList.Add("icons/d_lookdevclose@2x.png");
            _pathList.Add("icons/d_lookdevenvrotation.png");
            _pathList.Add("icons/d_lookdevenvrotation@2x.png");
            _pathList.Add("icons/d_lookdevmirrorviews.png");
            _pathList.Add("icons/d_lookdevmirrorviews@2x.png");
            _pathList.Add("icons/d_lookdevmirrorviewsactive.png");
            _pathList.Add("icons/d_lookdevmirrorviewsactive@2x.png");
            _pathList.Add("icons/d_lookdevmirrorviewsinactive.png");
            _pathList.Add("icons/d_lookdevmirrorviewsinactive@2x.png");
            _pathList.Add("icons/d_lookdevobjrotation.png");
            _pathList.Add("icons/d_lookdevobjrotation@2x.png");
            _pathList.Add("icons/d_lookdevpaneoption.png");
            _pathList.Add("icons/d_lookdevpaneoption@2x.png");
            _pathList.Add("icons/d_lookdevresetenv.png");
            _pathList.Add("icons/d_lookdevresetenv@2x.png");
            _pathList.Add("icons/d_lookdevshadow.png");
            _pathList.Add("icons/d_lookdevshadow@2x.png");
            _pathList.Add("icons/d_lookdevsidebyside.png");
            _pathList.Add("icons/d_lookdevsidebyside@2x.png");
            _pathList.Add("icons/d_lookdevsingle1.png");
            _pathList.Add("icons/d_lookdevsingle1@2x.png");
            _pathList.Add("icons/d_lookdevsingle2.png");
            _pathList.Add("icons/d_lookdevsingle2@2x.png");
            _pathList.Add("icons/d_lookdevsplit.png");
            _pathList.Add("icons/d_lookdevsplit@2x.png");
            _pathList.Add("icons/d_lookdevzone.png");
            _pathList.Add("icons/d_lookdevzone@2x.png");
            _pathList.Add("icons/d_mirror.png");
            _pathList.Add("icons/d_model large.png");
            _pathList.Add("icons/d_monologo.png");
            _pathList.Add("icons/d_movetool on.png");
            _pathList.Add("icons/d_movetool.png");
            _pathList.Add("icons/d_navigation.png");
            _pathList.Add("icons/d_occlusion.png");
            _pathList.Add("icons/d_p4_addedlocal.png");
            _pathList.Add("icons/d_p4_addedremote.png");
            _pathList.Add("icons/d_p4_checkoutlocal.png");
            _pathList.Add("icons/d_p4_checkoutremote.png");
            _pathList.Add("icons/d_p4_conflicted.png");
            _pathList.Add("icons/d_p4_deletedlocal.png");
            _pathList.Add("icons/d_p4_deletedremote.png");
            _pathList.Add("icons/d_p4_local.png");
            _pathList.Add("icons/d_p4_lockedlocal.png");
            _pathList.Add("icons/d_p4_lockedremote.png");
            _pathList.Add("icons/d_p4_outofsync.png");
            _pathList.Add("icons/d_particle effect.png");
            _pathList.Add("icons/d_pausebutton anim.png");
            _pathList.Add("icons/d_pausebutton on.png");
            _pathList.Add("icons/d_pausebutton.png");
            _pathList.Add("icons/d_playbutton anim.png");
            _pathList.Add("icons/d_playbutton on.png");
            _pathList.Add("icons/d_playbutton.png");
            _pathList.Add("icons/d_playbuttonprofile anim.png");
            _pathList.Add("icons/d_playbuttonprofile on.png");
            _pathList.Add("icons/d_playbuttonprofile.png");
            _pathList.Add("icons/d_playloopoff.png");
            _pathList.Add("icons/d_playloopon.png");
            _pathList.Add("icons/d_preaudioautoplayoff.png");
            _pathList.Add("icons/d_preaudioautoplayon.png");
            _pathList.Add("icons/d_preaudioloopoff.png");
            _pathList.Add("icons/d_preaudioloopon.png");
            _pathList.Add("icons/d_preaudioplayoff.png");
            _pathList.Add("icons/d_preaudioplayon.png");
            _pathList.Add("icons/d_prematcube.png");
            _pathList.Add("icons/d_prematcylinder.png");
            _pathList.Add("icons/d_prematlight0.png");
            _pathList.Add("icons/d_prematlight1.png");
            _pathList.Add("icons/d_prematsphere.png");
            _pathList.Add("icons/d_premattorus.png");
            _pathList.Add("icons/d_pretexturealpha.png");
            _pathList.Add("icons/d_pretexturemipmaphigh.png");
            _pathList.Add("icons/d_pretexturemipmaplow.png");
            _pathList.Add("icons/d_pretexturergb.png");
            _pathList.Add("icons/d_profiler.audio.png");
            _pathList.Add("icons/d_profiler.cpu.png");
            _pathList.Add("icons/d_profiler.firstframe.png");
            _pathList.Add("icons/d_profiler.gpu.png");
            _pathList.Add("icons/d_profiler.lastframe.png");
            _pathList.Add("icons/d_profiler.memory.png");
            _pathList.Add("icons/d_profiler.network.png");
            _pathList.Add("icons/d_profiler.nextframe.png");
            _pathList.Add("icons/d_profiler.physics.png");
            _pathList.Add("icons/d_profiler.prevframe.png");
            _pathList.Add("icons/d_profiler.record.png");
            _pathList.Add("icons/d_profiler.rendering.png");
            _pathList.Add("icons/d_profiler.video.png");
            _pathList.Add("icons/d_profilercolumn.warningcount.png");
            _pathList.Add("icons/d_project.png");
            _pathList.Add("icons/d_recttool on.png");
            _pathList.Add("icons/d_recttool.png");
            _pathList.Add("icons/d_recttransformblueprint.png");
            _pathList.Add("icons/d_recttransformraw.png");
            _pathList.Add("icons/d_redgroove.png");
            _pathList.Add("icons/d_refresh.png");
            _pathList.Add("icons/d_renderdoc.png");
            _pathList.Add("icons/d_rightbracket.png");
            _pathList.Add("icons/d_rotatetool on.png");
            _pathList.Add("icons/d_rotatetool.png");
            _pathList.Add("icons/d_scaletool on.png");
            _pathList.Add("icons/d_scaletool.png");
            _pathList.Add("icons/d_sceneviewalpha.png");
            _pathList.Add("icons/d_sceneviewaudio.png");
            _pathList.Add("icons/d_sceneviewfx.png");
            _pathList.Add("icons/d_sceneviewlighting.png");
            _pathList.Add("icons/d_sceneviewortho.png");
            _pathList.Add("icons/d_sceneviewrgb.png");
            _pathList.Add("icons/d_scrollshadow.png");
            _pathList.Add("icons/d_settingsicon.png");
            _pathList.Add("icons/d_socialnetworks.facebookshare.png");
            _pathList.Add("icons/d_socialnetworks.linkedinshare.png");
            _pathList.Add("icons/d_socialnetworks.tweet.png");
            _pathList.Add("icons/d_socialnetworks.udnopen.png");
            _pathList.Add("icons/d_speedscale.png");
            _pathList.Add("icons/d_stepbutton anim.png");
            _pathList.Add("icons/d_stepbutton on.png");
            _pathList.Add("icons/d_stepbutton.png");
            _pathList.Add("icons/d_stepleftbutton-on.png");
            _pathList.Add("icons/d_stepleftbutton.png");
            _pathList.Add("icons/d_svn_addedlocal.png");
            _pathList.Add("icons/d_svn_conflicted.png");
            _pathList.Add("icons/d_svn_deletedlocal.png");
            _pathList.Add("icons/d_svn_local.png");
            _pathList.Add("icons/d_svn_lockedlocal.png");
            _pathList.Add("icons/d_svn_outofsync.png");
            _pathList.Add("icons/d_terraininspector.terraintoollower on.png");
            _pathList.Add("icons/d_terraininspector.terraintoolloweralt.png");
            _pathList.Add("icons/d_terraininspector.terraintoolplants on.png");
            _pathList.Add("icons/d_terraininspector.terraintoolplants.png");
            _pathList.Add("icons/d_terraininspector.terraintoolplantsalt on.png");
            _pathList.Add("icons/d_terraininspector.terraintoolplantsalt.png");
            _pathList.Add("icons/d_terraininspector.terraintoolraise on.png");
            _pathList.Add("icons/d_terraininspector.terraintoolraise.png");
            _pathList.Add("icons/d_terraininspector.terraintoolsetheight on.png");
            _pathList.Add("icons/d_terraininspector.terraintoolsetheight.png");
            _pathList.Add("icons/d_terraininspector.terraintoolsetheightalt on.png");
            _pathList.Add("icons/d_terraininspector.terraintoolsetheightalt.png");
            _pathList.Add("icons/d_terraininspector.terraintoolsettings on.png");
            _pathList.Add("icons/d_terraininspector.terraintoolsettings.png");
            _pathList.Add("icons/d_terraininspector.terraintoolsmoothheight on.png");
            _pathList.Add("icons/d_terraininspector.terraintoolsmoothheight.png");
            _pathList.Add("icons/d_terraininspector.terraintoolsplat on.png");
            _pathList.Add("icons/d_terraininspector.terraintoolsplat.png");
            _pathList.Add("icons/d_terraininspector.terraintoolsplatalt on.png");
            _pathList.Add("icons/d_terraininspector.terraintoolsplatalt.png");
            _pathList.Add("icons/d_terraininspector.terraintooltrees on.png");
            _pathList.Add("icons/d_terraininspector.terraintooltrees.png");
            _pathList.Add("icons/d_terraininspector.terraintooltreesalt on.png");
            _pathList.Add("icons/d_terraininspector.terraintooltreesalt.png");
            _pathList.Add("icons/d_toolbar minus.png");
            _pathList.Add("icons/d_toolbar plus more.png");
            _pathList.Add("icons/d_toolbar plus.png");
            _pathList.Add("icons/d_toolhandlecenter.png");
            _pathList.Add("icons/d_toolhandleglobal.png");
            _pathList.Add("icons/d_toolhandlelocal.png");
            _pathList.Add("icons/d_toolhandlepivot.png");
            _pathList.Add("icons/d_tranp.png");
            _pathList.Add("icons/d_tree_icon.png");
            _pathList.Add("icons/d_tree_icon_branch.png");
            _pathList.Add("icons/d_tree_icon_branch_frond.png");
            _pathList.Add("icons/d_tree_icon_frond.png");
            _pathList.Add("icons/d_tree_icon_leaf.png");
            _pathList.Add("icons/d_treeeditor.addbranches.png");
            _pathList.Add("icons/d_treeeditor.addleaves.png");
            _pathList.Add("icons/d_treeeditor.branch on.png");
            _pathList.Add("icons/d_treeeditor.branch.png");
            _pathList.Add("icons/d_treeeditor.branchfreehand on.png");
            _pathList.Add("icons/d_treeeditor.branchfreehand.png");
            _pathList.Add("icons/d_treeeditor.branchrotate on.png");
            _pathList.Add("icons/d_treeeditor.branchrotate.png");
            _pathList.Add("icons/d_treeeditor.branchscale on.png");
            _pathList.Add("icons/d_treeeditor.branchscale.png");
            _pathList.Add("icons/d_treeeditor.branchtranslate on.png");
            _pathList.Add("icons/d_treeeditor.branchtranslate.png");
            _pathList.Add("icons/d_treeeditor.distribution on.png");
            _pathList.Add("icons/d_treeeditor.distribution.png");
            _pathList.Add("icons/d_treeeditor.duplicate.png");
            _pathList.Add("icons/d_treeeditor.geometry on.png");
            _pathList.Add("icons/d_treeeditor.geometry.png");
            _pathList.Add("icons/d_treeeditor.leaf on.png");
            _pathList.Add("icons/d_treeeditor.leaf.png");
            _pathList.Add("icons/d_treeeditor.leaffreehand on.png");
            _pathList.Add("icons/d_treeeditor.leaffreehand.png");
            _pathList.Add("icons/d_treeeditor.leafrotate on.png");
            _pathList.Add("icons/d_treeeditor.leafrotate.png");
            _pathList.Add("icons/d_treeeditor.leafscale on.png");
            _pathList.Add("icons/d_treeeditor.leafscale.png");
            _pathList.Add("icons/d_treeeditor.leaftranslate on.png");
            _pathList.Add("icons/d_treeeditor.leaftranslate.png");
            _pathList.Add("icons/d_treeeditor.material on.png");
            _pathList.Add("icons/d_treeeditor.material.png");
            _pathList.Add("icons/d_treeeditor.refresh.png");
            _pathList.Add("icons/d_treeeditor.trash.png");
            _pathList.Add("icons/d_treeeditor.wind on.png");
            _pathList.Add("icons/d_treeeditor.wind.png");
            _pathList.Add("icons/d_unityeditor.animationwindow.png");
            _pathList.Add("icons/d_unityeditor.consolewindow.png");
            _pathList.Add("icons/d_unityeditor.debuginspectorwindow.png");
            _pathList.Add("icons/d_unityeditor.finddependencies.png");
            _pathList.Add("icons/d_unityeditor.gameview.png");
            _pathList.Add("icons/d_unityeditor.hierarchywindow.png");
            _pathList.Add("icons/d_unityeditor.inspectorwindow.png");
            _pathList.Add("icons/d_unityeditor.lookdevview.png");
            _pathList.Add("icons/d_unityeditor.profilerwindow.png");
            _pathList.Add("icons/d_unityeditor.scenehierarchywindow.png");
            _pathList.Add("icons/d_unityeditor.sceneview.png");
            _pathList.Add("icons/d_unityeditor.serverview.png");
            _pathList.Add("icons/d_unityeditor.versioncontrol.png");
            _pathList.Add("icons/d_unitylogo.png");
            _pathList.Add("icons/d_verticalsplit.png");
            _pathList.Add("icons/d_viewtoolmove on.png");
            _pathList.Add("icons/d_viewtoolmove.png");
            _pathList.Add("icons/d_viewtoolorbit on.png");
            _pathList.Add("icons/d_viewtoolorbit.png");
            _pathList.Add("icons/d_viewtoolzoom on.png");
            _pathList.Add("icons/d_viewtoolzoom.png");
            _pathList.Add("icons/d_visibilityoff.png");
            _pathList.Add("icons/d_visibilityon.png");
            _pathList.Add("icons/d_vumetertexturehorizontal.png");
            _pathList.Add("icons/d_vumetertexturevertical.png");
            _pathList.Add("icons/d_waitspin00.png");
            _pathList.Add("icons/d_waitspin01.png");
            _pathList.Add("icons/d_waitspin02.png");
            _pathList.Add("icons/d_waitspin03.png");
            _pathList.Add("icons/d_waitspin04.png");
            _pathList.Add("icons/d_waitspin05.png");
            _pathList.Add("icons/d_waitspin06.png");
            _pathList.Add("icons/d_waitspin07.png");
            _pathList.Add("icons/d_waitspin08.png");
            _pathList.Add("icons/d_waitspin09.png");
            _pathList.Add("icons/d_waitspin10.png");
            _pathList.Add("icons/d_waitspin11.png");
            _pathList.Add("icons/d_welcomescreen.asset");
            _pathList.Add("icons/d_winbtn_graph.png");
            _pathList.Add("icons/d_winbtn_graph_close_h.png");
            _pathList.Add("icons/d_winbtn_graph_max_h.png");
            _pathList.Add("icons/d_winbtn_graph_min_h.png");
            _pathList.Add("icons/d_winbtn_mac_close.png");
            _pathList.Add("icons/d_winbtn_mac_close_a.png");
            _pathList.Add("icons/d_winbtn_mac_close_h.png");
            _pathList.Add("icons/d_winbtn_mac_inact.png");
            _pathList.Add("icons/d_winbtn_mac_max.png");
            _pathList.Add("icons/d_winbtn_mac_max_a.png");
            _pathList.Add("icons/d_winbtn_mac_max_h.png");
            _pathList.Add("icons/d_winbtn_mac_min.png");
            _pathList.Add("icons/d_winbtn_mac_min_a.png");
            _pathList.Add("icons/d_winbtn_mac_min_h.png");
            _pathList.Add("icons/d_winbtn_win_close.png");
            _pathList.Add("icons/d_winbtn_win_close_a.png");
            _pathList.Add("icons/d_winbtn_win_close_h.png");
            _pathList.Add("icons/d_winbtn_win_max.png");
            _pathList.Add("icons/d_winbtn_win_max_a.png");
            _pathList.Add("icons/d_winbtn_win_max_h.png");
            _pathList.Add("icons/d_winbtn_win_min.png");
            _pathList.Add("icons/d_winbtn_win_min_a.png");
            _pathList.Add("icons/d_winbtn_win_min_h.png");
            _pathList.Add("icons/d_winbtn_win_rest.png");
            _pathList.Add("icons/d_winbtn_win_rest_a.png");
            _pathList.Add("icons/d_winbtn_win_rest_h.png");
            _pathList.Add("icons/defaultsorting.png");
            _pathList.Add("icons/editcollider.png");
            _pathList.Add("icons/editicon.sml.png");
            _pathList.Add("icons/endbutton-on.png");
            _pathList.Add("icons/endbutton.png");
            _pathList.Add("icons/eyedropper.large.png");
            _pathList.Add("icons/eyedropper.sml.png");
            _pathList.Add("icons/favorite.png");
            _pathList.Add("icons/filterbylabel.png");
            _pathList.Add("icons/filterbytype.png");
            _pathList.Add("icons/gear.png");
            _pathList.Add("icons/groove.png");
            _pathList.Add("icons/guisystem/align_horizontally.png");
            _pathList.Add("icons/guisystem/align_horizontally_center.png");
            _pathList.Add("icons/guisystem/align_horizontally_center_active.png");
            _pathList.Add("icons/guisystem/align_horizontally_left.png");
            _pathList.Add("icons/guisystem/align_horizontally_left_active.png");
            _pathList.Add("icons/guisystem/align_horizontally_right.png");
            _pathList.Add("icons/guisystem/align_horizontally_right_active.png");
            _pathList.Add("icons/guisystem/align_vertically.png");
            _pathList.Add("icons/guisystem/align_vertically_bottom.png");
            _pathList.Add("icons/guisystem/align_vertically_bottom_active.png");
            _pathList.Add("icons/guisystem/align_vertically_center.png");
            _pathList.Add("icons/guisystem/align_vertically_center_active.png");
            _pathList.Add("icons/guisystem/align_vertically_top.png");
            _pathList.Add("icons/guisystem/align_vertically_top_active.png");
            _pathList.Add("icons/guisystem/d_align_horizontally.png");
            _pathList.Add("icons/guisystem/d_align_horizontally_center.png");
            _pathList.Add("icons/guisystem/d_align_horizontally_center_active.png");
            _pathList.Add("icons/guisystem/d_align_horizontally_left.png");
            _pathList.Add("icons/guisystem/d_align_horizontally_left_active.png");
            _pathList.Add("icons/guisystem/d_align_horizontally_right.png");
            _pathList.Add("icons/guisystem/d_align_horizontally_right_active.png");
            _pathList.Add("icons/guisystem/d_align_vertically.png");
            _pathList.Add("icons/guisystem/d_align_vertically_bottom.png");
            _pathList.Add("icons/guisystem/d_align_vertically_bottom_active.png");
            _pathList.Add("icons/guisystem/d_align_vertically_center.png");
            _pathList.Add("icons/guisystem/d_align_vertically_center_active.png");
            _pathList.Add("icons/guisystem/d_align_vertically_top.png");
            _pathList.Add("icons/guisystem/d_align_vertically_top_active.png");
            _pathList.Add("icons/horizontalsplit.png");
            _pathList.Add("icons/icon dropdown.png");
            _pathList.Add("icons/in-addcomponentleft.png");
            _pathList.Add("icons/in-addcomponentright.png");
            _pathList.Add("icons/inspectorlock.png");
            _pathList.Add("icons/knobcshape.png");
            _pathList.Add("icons/knobcshapemini.png");
            _pathList.Add("icons/leftbracket.png");
            _pathList.Add("icons/lighting.png");
            _pathList.Add("icons/lightmapeditor.windowtitle.png");
            _pathList.Add("icons/lightmapping.png");
            _pathList.Add("icons/lightmeter/d_greenlight.png");
            _pathList.Add("icons/lightmeter/d_lightoff.png");
            _pathList.Add("icons/lightmeter/d_lightrim.png");
            _pathList.Add("icons/lightmeter/d_orangelight.png");
            _pathList.Add("icons/lightmeter/d_redlight.png");
            _pathList.Add("icons/lightmeter/greenlight.png");
            _pathList.Add("icons/lightmeter/lightoff.png");
            _pathList.Add("icons/lightmeter/lightrim.png");
            _pathList.Add("icons/lightmeter/orangelight.png");
            _pathList.Add("icons/lightmeter/redlight.png");
            _pathList.Add("icons/lockicon-on.png");
            _pathList.Add("icons/lockicon.png");
            _pathList.Add("icons/lookdevcenterlight.png");
            _pathList.Add("icons/lookdevcenterlightl@2x.png");
            _pathList.Add("icons/lookdevclose.png");
            _pathList.Add("icons/lookdevclose@2x.png");
            _pathList.Add("icons/lookdevenvrotation.png");
            _pathList.Add("icons/lookdevenvrotation@2x.png");
            _pathList.Add("icons/lookdeveyedrop.png");
            _pathList.Add("icons/lookdevlight.png");
            _pathList.Add("icons/lookdevlight@2x.png");
            _pathList.Add("icons/lookdevmirrorviewsactive.png");
            _pathList.Add("icons/lookdevmirrorviewsactive@2x.png");
            _pathList.Add("icons/lookdevmirrorviewsinactive.png");
            _pathList.Add("icons/lookdevmirrorviewsinactive@2x.png");
            _pathList.Add("icons/lookdevobjrotation.png");
            _pathList.Add("icons/lookdevobjrotation@2x.png");
            _pathList.Add("icons/lookdevpaneoption.png");
            _pathList.Add("icons/lookdevpaneoption@2x.png");
            _pathList.Add("icons/lookdevresetenv.png");
            _pathList.Add("icons/lookdevresetenv@2x.png");
            _pathList.Add("icons/lookdevshadow.png");
            _pathList.Add("icons/lookdevshadow@2x.png");
            _pathList.Add("icons/lookdevshadowframe.png");
            _pathList.Add("icons/lookdevshadowframe@2x.png");
            _pathList.Add("icons/lookdevsidebyside.png");
            _pathList.Add("icons/lookdevsidebyside@2x.png");
            _pathList.Add("icons/lookdevsingle1.png");
            _pathList.Add("icons/lookdevsingle1@2x.png");
            _pathList.Add("icons/lookdevsingle2.png");
            _pathList.Add("icons/lookdevsingle2@2x.png");
            _pathList.Add("icons/lookdevsplit.png");
            _pathList.Add("icons/lookdevsplit@2x.png");
            _pathList.Add("icons/lookdevzone.png");
            _pathList.Add("icons/lookdevzone@2x.png");
            _pathList.Add("icons/loop.png");
            _pathList.Add("icons/mirror.png");
            _pathList.Add("icons/monologo.png");
            _pathList.Add("icons/movetool on.png");
            _pathList.Add("icons/movetool.png");
            _pathList.Add("icons/navigation.png");
            _pathList.Add("icons/occlusion.png");
            _pathList.Add("icons/p4_addedlocal.png");
            _pathList.Add("icons/p4_addedremote.png");
            _pathList.Add("icons/p4_blueleftparenthesis.png");
            _pathList.Add("icons/p4_bluerightparenthesis.png");
            _pathList.Add("icons/p4_checkoutlocal.png");
            _pathList.Add("icons/p4_checkoutremote.png");
            _pathList.Add("icons/p4_conflicted.png");
            _pathList.Add("icons/p4_deletedlocal.png");
            _pathList.Add("icons/p4_deletedremote.png");
            _pathList.Add("icons/p4_local.png");
            _pathList.Add("icons/p4_lockedlocal.png");
            _pathList.Add("icons/p4_lockedremote.png");
            _pathList.Add("icons/p4_outofsync.png");
            _pathList.Add("icons/p4_redleftparenthesis.png");
            _pathList.Add("icons/p4_redrightparenthesis.png");
            _pathList.Add("icons/particle effect.png");
            _pathList.Add("icons/pausebutton anim.png");
            _pathList.Add("icons/pausebutton on.png");
            _pathList.Add("icons/pausebutton.png");
            _pathList.Add("icons/playbutton anim.png");
            _pathList.Add("icons/playbutton on.png");
            _pathList.Add("icons/playbutton.png");
            _pathList.Add("icons/playbuttonprofile anim.png");
            _pathList.Add("icons/playbuttonprofile on.png");
            _pathList.Add("icons/playbuttonprofile.png");
            _pathList.Add("icons/playloopoff.png");
            _pathList.Add("icons/playloopon.png");
            _pathList.Add("icons/playspeed.png");
            _pathList.Add("icons/preaudioautoplayoff.png");
            _pathList.Add("icons/preaudioautoplayon.png");
            _pathList.Add("icons/preaudioloopoff.png");
            _pathList.Add("icons/preaudioloopon.png");
            _pathList.Add("icons/preaudioplayoff.png");
            _pathList.Add("icons/preaudioplayon.png");
            _pathList.Add("icons/prematcube.png");
            _pathList.Add("icons/prematcylinder.png");
            _pathList.Add("icons/prematlight0.png");
            _pathList.Add("icons/prematlight1.png");
            _pathList.Add("icons/prematquad.png");
            _pathList.Add("icons/prematsphere.png");
            _pathList.Add("icons/premattorus.png");
            _pathList.Add("icons/pretexturealpha.png");
            _pathList.Add("icons/pretexturemipmaphigh.png");
            _pathList.Add("icons/pretexturemipmaplow.png");
            _pathList.Add("icons/pretexturergb.png");
            _pathList.Add("icons/processed/animation icon.asset");
            _pathList.Add("icons/processed/animationclip icon.asset");
            _pathList.Add("icons/processed/animator icon.asset");
            _pathList.Add("icons/processed/animatorcontroller icon.asset");
            _pathList.Add("icons/processed/animatoroverridecontroller icon.asset");
            _pathList.Add("icons/processed/animatorstate icon.asset");
            _pathList.Add("icons/processed/animatorstatemachine icon.asset");
            _pathList.Add("icons/processed/animatorstatetransition icon.asset");
            _pathList.Add("icons/processed/anystatenode icon.asset");
            _pathList.Add("icons/processed/areaeffector2d icon.asset");
            _pathList.Add("icons/processed/arealight gizmo.asset");
            _pathList.Add("icons/processed/arealight icon.asset");
            _pathList.Add("icons/processed/assetstore icon.asset");
            _pathList.Add("icons/processed/audiochorusfilter icon.asset");
            _pathList.Add("icons/processed/audioclip icon.asset");
            _pathList.Add("icons/processed/audiodistortionfilter icon.asset");
            _pathList.Add("icons/processed/audioechofilter icon.asset");
            _pathList.Add("icons/processed/audiohighpassfilter icon.asset");
            _pathList.Add("icons/processed/audiolistener icon.asset");
            _pathList.Add("icons/processed/audiolowpassfilter icon.asset");
            _pathList.Add("icons/processed/audiomixercontroller icon.asset");
            _pathList.Add("icons/processed/audiomixergroup icon.asset");
            _pathList.Add("icons/processed/audiomixersnapshot icon.asset");
            _pathList.Add("icons/processed/audiomixerview icon.asset");
            _pathList.Add("icons/processed/audioreverbfilter icon.asset");
            _pathList.Add("icons/processed/audioreverbzone icon.asset");
            _pathList.Add("icons/processed/audiosource gizmo.asset");
            _pathList.Add("icons/processed/audiosource icon.asset");
            _pathList.Add("icons/processed/avatar icon.asset");
            _pathList.Add("icons/processed/avatarmask icon.asset");
            _pathList.Add("icons/processed/billboardasset icon.asset");
            _pathList.Add("icons/processed/billboardrenderer icon.asset");
            _pathList.Add("icons/processed/blendtree icon.asset");
            _pathList.Add("icons/processed/boo script icon.asset");
            _pathList.Add("icons/processed/boxcollider icon.asset");
            _pathList.Add("icons/processed/boxcollider2d icon.asset");
            _pathList.Add("icons/processed/buoyancyeffector2d icon.asset");
            _pathList.Add("icons/processed/camera gizmo.asset");
            _pathList.Add("icons/processed/camera icon.asset");
            _pathList.Add("icons/processed/canvas icon.asset");
            _pathList.Add("icons/processed/canvasgroup icon.asset");
            _pathList.Add("icons/processed/canvasrenderer icon.asset");
            _pathList.Add("icons/processed/capsulecollider icon.asset");
            _pathList.Add("icons/processed/capsulecollider2d icon.asset");
            _pathList.Add("icons/processed/cgprogram icon.asset");
            _pathList.Add("icons/processed/charactercontroller icon.asset");
            _pathList.Add("icons/processed/characterjoint icon.asset");
            _pathList.Add("icons/processed/chorusfilter icon.asset");
            _pathList.Add("icons/processed/circlecollider2d icon.asset");
            _pathList.Add("icons/processed/cloth icon.asset");
            _pathList.Add("icons/processed/collabchanges icon.asset");
            _pathList.Add("icons/processed/collabchangesconflict icon.asset");
            _pathList.Add("icons/processed/collabchangesdeleted icon.asset");
            _pathList.Add("icons/processed/collabconflict icon.asset");
            _pathList.Add("icons/processed/collabcreate icon.asset");
            _pathList.Add("icons/processed/collabdeleted icon.asset");
            _pathList.Add("icons/processed/collabedit icon.asset");
            _pathList.Add("icons/processed/collabexclude icon.asset");
            _pathList.Add("icons/processed/collabmoved icon.asset");
            _pathList.Add("icons/processed/compositecollider2d icon.asset");
            _pathList.Add("icons/processed/computeshader icon.asset");
            _pathList.Add("icons/processed/configurablejoint icon.asset");
            _pathList.Add("icons/processed/constantforce icon.asset");
            _pathList.Add("icons/processed/constantforce2d icon.asset");
            _pathList.Add("icons/processed/cs script icon.asset");
            _pathList.Add("icons/processed/cubemap icon.asset");
            _pathList.Add("icons/processed/d_audiomixerview icon.asset");
            _pathList.Add("icons/processed/d_canvas icon.asset");
            _pathList.Add("icons/processed/d_canvasgroup icon.asset");
            _pathList.Add("icons/processed/d_canvasrenderer icon.asset");
            _pathList.Add("icons/processed/d_collabchanges icon.asset");
            _pathList.Add("icons/processed/d_collabchangesconflict icon.asset");
            _pathList.Add("icons/processed/d_collabchangesdeleted icon.asset");
            _pathList.Add("icons/processed/d_collabconflict icon.asset");
            _pathList.Add("icons/processed/d_collabcreate icon.asset");
            _pathList.Add("icons/processed/d_collabdeleted icon.asset");
            _pathList.Add("icons/processed/d_collabedit icon.asset");
            _pathList.Add("icons/processed/d_collabexclude icon.asset");
            _pathList.Add("icons/processed/d_collabmoved icon.asset");
            _pathList.Add("icons/processed/d_gridlayoutgroup icon.asset");
            _pathList.Add("icons/processed/d_horizontallayoutgroup icon.asset");
            _pathList.Add("icons/processed/d_lightprobeproxyvolume icon.asset");
            _pathList.Add("icons/processed/d_particlesystem icon.asset");
            _pathList.Add("icons/processed/d_recttransform icon.asset");
            _pathList.Add("icons/processed/d_sortinggroup icon.asset");
            _pathList.Add("icons/processed/d_verticallayoutgroup icon.asset");
            _pathList.Add("icons/processed/defaultasset icon.asset");
            _pathList.Add("icons/processed/defaultslate icon.asset");
            _pathList.Add("icons/processed/directionallight gizmo.asset");
            _pathList.Add("icons/processed/directionallight icon.asset");
            _pathList.Add("icons/processed/distancejoint2d icon.asset");
            _pathList.Add("icons/processed/echofilter icon.asset");
            _pathList.Add("icons/processed/edgecollider2d icon.asset");
            _pathList.Add("icons/processed/editorsettings icon.asset");
            _pathList.Add("icons/processed/favorite icon.asset");
            _pathList.Add("icons/processed/fixedjoint icon.asset");
            _pathList.Add("icons/processed/fixedjoint2d icon.asset");
            _pathList.Add("icons/processed/flare icon.asset");
            _pathList.Add("icons/processed/flarelayer icon.asset");
            _pathList.Add("icons/processed/folder icon.asset");
            _pathList.Add("icons/processed/folderempty icon.asset");
            _pathList.Add("icons/processed/folderfavorite icon.asset");
            _pathList.Add("icons/processed/font icon.asset");
            _pathList.Add("icons/processed/frictionjoint2d icon.asset");
            _pathList.Add("icons/processed/gamemanager icon.asset");
            _pathList.Add("icons/processed/gameobject icon.asset");
            _pathList.Add("icons/processed/gisraster icon.asset");
            _pathList.Add("icons/processed/gissplatdata icon.asset");
            _pathList.Add("icons/processed/gisterrain icon.asset");
            _pathList.Add("icons/processed/guilayer icon.asset");
            _pathList.Add("icons/processed/guiskin icon.asset");
            _pathList.Add("icons/processed/guitext icon.asset");
            _pathList.Add("icons/processed/guitexture icon.asset");
            _pathList.Add("icons/processed/halo icon.asset");
            _pathList.Add("icons/processed/highpassfilter icon.asset");
            _pathList.Add("icons/processed/hingejoint icon.asset");
            _pathList.Add("icons/processed/hingejoint2d icon.asset");
            _pathList.Add("icons/processed/horizontallayoutgroup icon.asset");
            _pathList.Add("icons/processed/humantemplate icon.asset");
            _pathList.Add("icons/processed/js script icon.asset");
            _pathList.Add("icons/processed/lensflare gizmo.asset");
            _pathList.Add("icons/processed/lensflare icon.asset");
            _pathList.Add("icons/processed/light icon.asset");
            _pathList.Add("icons/processed/lightingdataasset icon.asset");
            _pathList.Add("icons/processed/lightmapparameters icon.asset");
            _pathList.Add("icons/processed/lightprobegroup gizmo.asset");
            _pathList.Add("icons/processed/lightprobegroup icon.asset");
            _pathList.Add("icons/processed/lightprobeproxyvolume gizmo.asset");
            _pathList.Add("icons/processed/lightprobeproxyvolume icon.asset");
            _pathList.Add("icons/processed/lightprobes icon.asset");
            _pathList.Add("icons/processed/linerenderer icon.asset");
            _pathList.Add("icons/processed/lodgroup icon.asset");
            _pathList.Add("icons/processed/lowpassfilter icon.asset");
            _pathList.Add("icons/processed/main light gizmo.asset");
            _pathList.Add("icons/processed/material icon.asset");
            _pathList.Add("icons/processed/mesh icon.asset");
            _pathList.Add("icons/processed/meshcollider icon.asset");
            _pathList.Add("icons/processed/meshfilter icon.asset");
            _pathList.Add("icons/processed/meshparticleemitter icon.asset");
            _pathList.Add("icons/processed/meshrenderer icon.asset");
            _pathList.Add("icons/processed/metafile icon.asset");
            _pathList.Add("icons/processed/microphone icon.asset");
            _pathList.Add("icons/processed/motion icon.asset");
            _pathList.Add("icons/processed/movietexture icon.asset");
            _pathList.Add("icons/processed/muscleclip icon.asset");
            _pathList.Add("icons/processed/navmeshagent icon.asset");
            _pathList.Add("icons/processed/navmeshdata icon.asset");
            _pathList.Add("icons/processed/navmeshobstacle icon.asset");
            _pathList.Add("icons/processed/networkview icon.asset");
            _pathList.Add("icons/processed/occlusionarea icon.asset");
            _pathList.Add("icons/processed/occlusionportal icon.asset");
            _pathList.Add("icons/processed/offmeshlink icon.asset");
            _pathList.Add("icons/processed/particleanimator icon.asset");
            _pathList.Add("icons/processed/particleemitter icon.asset");
            _pathList.Add("icons/processed/particlerenderer icon.asset");
            _pathList.Add("icons/processed/particlesystem gizmo.asset");
            _pathList.Add("icons/processed/particlesystem icon.asset");
            _pathList.Add("icons/processed/physicmaterial icon.asset");
            _pathList.Add("icons/processed/physicsmaterial2d icon.asset");
            _pathList.Add("icons/processed/platformeffector2d icon.asset");
            _pathList.Add("icons/processed/pointeffector2d icon.asset");
            _pathList.Add("icons/processed/pointlight gizmo.asset");
            _pathList.Add("icons/processed/polygoncollider2d icon.asset");
            _pathList.Add("icons/processed/prefab icon.asset");
            _pathList.Add("icons/processed/prefabmodel icon.asset");
            _pathList.Add("icons/processed/prefabnormal icon.asset");
            _pathList.Add("icons/processed/proceduralmaterial icon.asset");
            _pathList.Add("icons/processed/projector gizmo.asset");
            _pathList.Add("icons/processed/projector icon.asset");
            _pathList.Add("icons/processed/raycastcollider icon.asset");
            _pathList.Add("icons/processed/recttransform icon.asset");
            _pathList.Add("icons/processed/reflectionprobe gizmo.asset");
            _pathList.Add("icons/processed/reflectionprobe icon.asset");
            _pathList.Add("icons/processed/relativejoint2d icon.asset");
            _pathList.Add("icons/processed/rendertexture icon.asset");
            _pathList.Add("icons/processed/reverbfilter icon.asset");
            _pathList.Add("icons/processed/rigidbody icon.asset");
            _pathList.Add("icons/processed/rigidbody2d icon.asset");
            _pathList.Add("icons/processed/sceneasset icon.asset");
            _pathList.Add("icons/processed/sceneset icon.asset");
            _pathList.Add("icons/processed/scriptableobject icon.asset");
            _pathList.Add("icons/processed/search icon.asset");
            _pathList.Add("icons/processed/shader icon.asset");
            _pathList.Add("icons/processed/shadervariantcollection icon.asset");
            _pathList.Add("icons/processed/skinnedmeshrenderer icon.asset");
            _pathList.Add("icons/processed/skybox icon.asset");
            _pathList.Add("icons/processed/sliderjoint2d icon.asset");
            _pathList.Add("icons/processed/sortinggroup icon.asset");
            _pathList.Add("icons/processed/speedtreemodel icon.asset");
            _pathList.Add("icons/processed/spherecollider icon.asset");
            _pathList.Add("icons/processed/spotlight gizmo.asset");
            _pathList.Add("icons/processed/spotlight icon.asset");
            _pathList.Add("icons/processed/springjoint icon.asset");
            _pathList.Add("icons/processed/springjoint2d icon.asset");
            _pathList.Add("icons/processed/sprite icon.asset");
            _pathList.Add("icons/processed/spritecollider icon.asset");
            _pathList.Add("icons/processed/spriterenderer icon.asset");
            _pathList.Add("icons/processed/substancearchive icon.asset");
            _pathList.Add("icons/processed/surfaceeffector2d icon.asset");
            _pathList.Add("icons/processed/sv_icon_dot0_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot10_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot11_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot12_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot13_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot14_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot15_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot1_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot2_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot3_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot4_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot5_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot6_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot7_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot8_pix16_gizmo.asset");
            _pathList.Add("icons/processed/sv_icon_dot9_pix16_gizmo.asset");
            _pathList.Add("icons/processed/targetjoint2d icon.asset");
            _pathList.Add("icons/processed/terrain icon.asset");
            _pathList.Add("icons/processed/terraincollider icon.asset");
            _pathList.Add("icons/processed/terraindata icon.asset");
            _pathList.Add("icons/processed/textasset icon.asset");
            _pathList.Add("icons/processed/textmesh icon.asset");
            _pathList.Add("icons/processed/texture icon.asset");
            _pathList.Add("icons/processed/texture2d icon.asset");
            _pathList.Add("icons/processed/trailrenderer icon.asset");
            _pathList.Add("icons/processed/transform icon.asset");
            _pathList.Add("icons/processed/unityeditor/animationwindowevent icon.asset");
            _pathList.Add("icons/processed/unityengine/eventsystems/d_eventsystem icon.asset");
            _pathList.Add("icons/processed/unityengine/eventsystems/d_eventtrigger icon.asset");
            _pathList.Add("icons/processed/unityengine/eventsystems/d_physics2draycaster icon.asset");
            _pathList.Add("icons/processed/unityengine/eventsystems/d_physicsraycaster icon.asset");
            _pathList.Add("icons/processed/unityengine/eventsystems/d_standaloneinputmodule icon.asset");
            _pathList.Add("icons/processed/unityengine/eventsystems/d_touchinputmodule icon.asset");
            _pathList.Add("icons/processed/unityengine/eventsystems/eventsystem icon.asset");
            _pathList.Add("icons/processed/unityengine/eventsystems/eventtrigger icon.asset");
            _pathList.Add("icons/processed/unityengine/eventsystems/physics2draycaster icon.asset");
            _pathList.Add("icons/processed/unityengine/eventsystems/physicsraycaster icon.asset");
            _pathList.Add("icons/processed/unityengine/eventsystems/standaloneinputmodule icon.asset");
            _pathList.Add("icons/processed/unityengine/eventsystems/touchinputmodule icon.asset");
            _pathList.Add("icons/processed/unityengine/networking/networkanimator icon.asset");
            _pathList.Add("icons/processed/unityengine/networking/networkdiscovery icon.asset");
            _pathList.Add("icons/processed/unityengine/networking/networkidentity icon.asset");
            _pathList.Add("icons/processed/unityengine/networking/networklobbymanager icon.asset");
            _pathList.Add("icons/processed/unityengine/networking/networklobbyplayer icon.asset");
            _pathList.Add("icons/processed/unityengine/networking/networkmanager icon.asset");
            _pathList.Add("icons/processed/unityengine/networking/networkmanagerhud icon.asset");
            _pathList.Add("icons/processed/unityengine/networking/networkmigrationmanager icon.asset");
            _pathList.Add("icons/processed/unityengine/networking/networkproximitychecker icon.asset");
            _pathList.Add("icons/processed/unityengine/networking/networkstartposition icon.asset");
            _pathList.Add("icons/processed/unityengine/networking/networktransform icon.asset");
            _pathList.Add("icons/processed/unityengine/networking/networktransformchild icon.asset");
            _pathList.Add("icons/processed/unityengine/networking/networktransformvisualizer icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/aspectratiofitter icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/button icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/canvasscaler icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/contentsizefitter icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/d_aspectratiofitter icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/d_canvasscaler icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/d_contentsizefitter icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/d_freeformlayoutgroup icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/d_graphicraycaster icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/d_gridlayoutgroup icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/d_horizontallayoutgroup icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/d_layoutelement icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/d_physicalresolution icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/d_scrollviewarea icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/d_selectionlist icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/d_selectionlistitem icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/d_selectionlisttemplate icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/d_verticallayoutgroup icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/dropdown icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/freeformlayoutgroup icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/graphicraycaster icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/gridlayoutgroup icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/horizontallayoutgroup icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/image icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/inputfield icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/layoutelement icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/mask icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/outline icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/positionasuv1 icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/rawimage icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/rectmask2d icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/scrollbar icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/scrollrect icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/selectable icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/shadow icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/slider icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/text icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/toggle icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/togglegroup icon.asset");
            _pathList.Add("icons/processed/unityengine/ui/verticallayoutgroup icon.asset");
            _pathList.Add("icons/processed/verticallayoutgroup icon.asset");
            _pathList.Add("icons/processed/videoclip icon.asset");
            _pathList.Add("icons/processed/videoeffect icon.asset");
            _pathList.Add("icons/processed/videoplayer icon.asset");
            _pathList.Add("icons/processed/wheelcollider icon.asset");
            _pathList.Add("icons/processed/wheeljoint2d icon.asset");
            _pathList.Add("icons/processed/windzone gizmo.asset");
            _pathList.Add("icons/processed/windzone icon.asset");
            _pathList.Add("icons/processed/worldparticlecollider icon.asset");
            _pathList.Add("icons/profiler.audio.png");
            _pathList.Add("icons/profiler.cpu.png");
            _pathList.Add("icons/profiler.firstframe.png");
            _pathList.Add("icons/profiler.gpu.png");
            _pathList.Add("icons/profiler.instrumentation.png");
            _pathList.Add("icons/profiler.lastframe.png");
            _pathList.Add("icons/profiler.memory.png");
            _pathList.Add("icons/profiler.networkmessages.png");
            _pathList.Add("icons/profiler.networkoperations.png");
            _pathList.Add("icons/profiler.nextframe.png");
            _pathList.Add("icons/profiler.physics.png");
            _pathList.Add("icons/profiler.physics2d.png");
            _pathList.Add("icons/profiler.prevframe.png");
            _pathList.Add("icons/profiler.record.png");
            _pathList.Add("icons/profiler.rendering.png");
            _pathList.Add("icons/profiler.video.png");
            _pathList.Add("icons/profilercolumn.warningcount.png");
            _pathList.Add("icons/project.png");
            _pathList.Add("icons/recttool on.png");
            _pathList.Add("icons/recttool.png");
            _pathList.Add("icons/recttransformblueprint.png");
            _pathList.Add("icons/recttransformraw.png");
            _pathList.Add("icons/redgroove.png");
            _pathList.Add("icons/refresh.png");
            _pathList.Add("icons/renderdoc.png");
            _pathList.Add("icons/rightbracket.png");
            _pathList.Add("icons/rotatetool on.png");
            _pathList.Add("icons/rotatetool.png");
            _pathList.Add("icons/saveactive.png");
            _pathList.Add("icons/savefromplay.png");
            _pathList.Add("icons/savepassive.png");
            _pathList.Add("icons/scaletool on.png");
            _pathList.Add("icons/scaletool.png");
            _pathList.Add("icons/sceneloadin.png");
            _pathList.Add("icons/sceneloadout.png");
            _pathList.Add("icons/scenesave.png");
            _pathList.Add("icons/scenesavegrey.png");
            _pathList.Add("icons/sceneviewalpha.png");
            _pathList.Add("icons/sceneviewaudio.png");
            _pathList.Add("icons/sceneviewfx.png");
            _pathList.Add("icons/sceneviewlighting.png");
            _pathList.Add("icons/sceneviewortho.png");
            _pathList.Add("icons/sceneviewrgb.png");
            _pathList.Add("icons/scrollshadow.png");
            _pathList.Add("icons/settingsicon.png");
            _pathList.Add("icons/socialnetworks.facebookshare.png");
            _pathList.Add("icons/socialnetworks.linkedinshare.png");
            _pathList.Add("icons/socialnetworks.tweet.png");
            _pathList.Add("icons/socialnetworks.udnlogo.png");
            _pathList.Add("icons/socialnetworks.udnopen.png");
            _pathList.Add("icons/speedscale.png");
            _pathList.Add("icons/statemachineeditor.arrowtip.png");
            _pathList.Add("icons/statemachineeditor.arrowtipselected.png");
            _pathList.Add("icons/statemachineeditor.background.png");
            _pathList.Add("icons/statemachineeditor.state.png");
            _pathList.Add("icons/statemachineeditor.statehover.png");
            _pathList.Add("icons/statemachineeditor.stateselected.png");
            _pathList.Add("icons/statemachineeditor.statesub.png");
            _pathList.Add("icons/statemachineeditor.statesubhover.png");
            _pathList.Add("icons/statemachineeditor.statesubselected.png");
            _pathList.Add("icons/statemachineeditor.upbutton.png");
            _pathList.Add("icons/statemachineeditor.upbuttonhover.png");
            _pathList.Add("icons/stepbutton anim.png");
            _pathList.Add("icons/stepbutton on.png");
            _pathList.Add("icons/stepbutton.png");
            _pathList.Add("icons/stepleftbutton-on.png");
            _pathList.Add("icons/stepleftbutton.png");
            _pathList.Add("icons/sticky_arrow.png");
            _pathList.Add("icons/sticky_p4.png");
            _pathList.Add("icons/sticky_skin.png");
            _pathList.Add("icons/sv_icon_dot0_sml.png");
            _pathList.Add("icons/sv_icon_dot10_sml.png");
            _pathList.Add("icons/sv_icon_dot11_sml.png");
            _pathList.Add("icons/sv_icon_dot12_sml.png");
            _pathList.Add("icons/sv_icon_dot13_sml.png");
            _pathList.Add("icons/sv_icon_dot14_sml.png");
            _pathList.Add("icons/sv_icon_dot15_sml.png");
            _pathList.Add("icons/sv_icon_dot1_sml.png");
            _pathList.Add("icons/sv_icon_dot2_sml.png");
            _pathList.Add("icons/sv_icon_dot3_sml.png");
            _pathList.Add("icons/sv_icon_dot4_sml.png");
            _pathList.Add("icons/sv_icon_dot5_sml.png");
            _pathList.Add("icons/sv_icon_dot6_sml.png");
            _pathList.Add("icons/sv_icon_dot7_sml.png");
            _pathList.Add("icons/sv_icon_dot8_sml.png");
            _pathList.Add("icons/sv_icon_dot9_sml.png");
            _pathList.Add("icons/sv_icon_name0.png");
            _pathList.Add("icons/sv_icon_name1.png");
            _pathList.Add("icons/sv_icon_name2.png");
            _pathList.Add("icons/sv_icon_name3.png");
            _pathList.Add("icons/sv_icon_name4.png");
            _pathList.Add("icons/sv_icon_name5.png");
            _pathList.Add("icons/sv_icon_name6.png");
            _pathList.Add("icons/sv_icon_name7.png");
            _pathList.Add("icons/sv_icon_none.png");
            _pathList.Add("icons/sv_label_0.png");
            _pathList.Add("icons/sv_label_1.png");
            _pathList.Add("icons/sv_label_2.png");
            _pathList.Add("icons/sv_label_3.png");
            _pathList.Add("icons/sv_label_4.png");
            _pathList.Add("icons/sv_label_5.png");
            _pathList.Add("icons/sv_label_6.png");
            _pathList.Add("icons/sv_label_7.png");
            _pathList.Add("icons/svn_addedlocal.png");
            _pathList.Add("icons/svn_conflicted.png");
            _pathList.Add("icons/svn_deletedlocal.png");
            _pathList.Add("icons/svn_local.png");
            _pathList.Add("icons/svn_lockedlocal.png");
            _pathList.Add("icons/svn_outofsync.png");
            _pathList.Add("icons/terraininspector.terraintoollower on.png");
            _pathList.Add("icons/terraininspector.terraintoollower.png");
            _pathList.Add("icons/terraininspector.terraintoolloweralt.png");
            _pathList.Add("icons/terraininspector.terraintoolplants on.png");
            _pathList.Add("icons/terraininspector.terraintoolplants.png");
            _pathList.Add("icons/terraininspector.terraintoolplantsalt on.png");
            _pathList.Add("icons/terraininspector.terraintoolplantsalt.png");
            _pathList.Add("icons/terraininspector.terraintoolraise on.png");
            _pathList.Add("icons/terraininspector.terraintoolraise.png");
            _pathList.Add("icons/terraininspector.terraintoolsetheight on.png");
            _pathList.Add("icons/terraininspector.terraintoolsetheight.png");
            _pathList.Add("icons/terraininspector.terraintoolsetheightalt on.png");
            _pathList.Add("icons/terraininspector.terraintoolsetheightalt.png");
            _pathList.Add("icons/terraininspector.terraintoolsettings on.png");
            _pathList.Add("icons/terraininspector.terraintoolsettings.png");
            _pathList.Add("icons/terraininspector.terraintoolsmoothheight on.png");
            _pathList.Add("icons/terraininspector.terraintoolsmoothheight.png");
            _pathList.Add("icons/terraininspector.terraintoolsplat on.png");
            _pathList.Add("icons/terraininspector.terraintoolsplat.png");
            _pathList.Add("icons/terraininspector.terraintoolsplatalt on.png");
            _pathList.Add("icons/terraininspector.terraintoolsplatalt.png");
            _pathList.Add("icons/terraininspector.terraintooltrees on.png");
            _pathList.Add("icons/terraininspector.terraintooltrees.png");
            _pathList.Add("icons/terraininspector.terraintooltreesalt on.png");
            _pathList.Add("icons/terraininspector.terraintooltreesalt.png");
            _pathList.Add("icons/testfailed.png");
            _pathList.Add("icons/testignored.png");
            _pathList.Add("icons/testinconclusive.png");
            _pathList.Add("icons/testnormal.png");
            _pathList.Add("icons/testpassed.png");
            _pathList.Add("icons/teststopwatch.png");
            _pathList.Add("icons/toolbar minus.png");
            _pathList.Add("icons/toolbar plus more.png");
            _pathList.Add("icons/toolbar plus.png");
            _pathList.Add("icons/toolhandlecenter.png");
            _pathList.Add("icons/toolhandleglobal.png");
            _pathList.Add("icons/toolhandlelocal.png");
            _pathList.Add("icons/toolhandlepivot.png");
            _pathList.Add("icons/tranp.png");
            _pathList.Add("icons/tree_icon.png");
            _pathList.Add("icons/tree_icon_branch.png");
            _pathList.Add("icons/tree_icon_branch_frond.png");
            _pathList.Add("icons/tree_icon_frond.png");
            _pathList.Add("icons/tree_icon_leaf.png");
            _pathList.Add("icons/treeeditor.addbranches.png");
            _pathList.Add("icons/treeeditor.addleaves.png");
            _pathList.Add("icons/treeeditor.branch on.png");
            _pathList.Add("icons/treeeditor.branch.png");
            _pathList.Add("icons/treeeditor.branchfreehand on.png");
            _pathList.Add("icons/treeeditor.branchfreehand.png");
            _pathList.Add("icons/treeeditor.branchrotate on.png");
            _pathList.Add("icons/treeeditor.branchrotate.png");
            _pathList.Add("icons/treeeditor.branchscale on.png");
            _pathList.Add("icons/treeeditor.branchscale.png");
            _pathList.Add("icons/treeeditor.branchtranslate on.png");
            _pathList.Add("icons/treeeditor.branchtranslate.png");
            _pathList.Add("icons/treeeditor.distribution on.png");
            _pathList.Add("icons/treeeditor.distribution.png");
            _pathList.Add("icons/treeeditor.duplicate.png");
            _pathList.Add("icons/treeeditor.geometry on.png");
            _pathList.Add("icons/treeeditor.geometry.png");
            _pathList.Add("icons/treeeditor.leaf on.png");
            _pathList.Add("icons/treeeditor.leaf.png");
            _pathList.Add("icons/treeeditor.leaffreehand on.png");
            _pathList.Add("icons/treeeditor.leaffreehand.png");
            _pathList.Add("icons/treeeditor.leafrotate on.png");
            _pathList.Add("icons/treeeditor.leafrotate.png");
            _pathList.Add("icons/treeeditor.leafscale on.png");
            _pathList.Add("icons/treeeditor.leafscale.png");
            _pathList.Add("icons/treeeditor.leaftranslate on.png");
            _pathList.Add("icons/treeeditor.leaftranslate.png");
            _pathList.Add("icons/treeeditor.material on.png");
            _pathList.Add("icons/treeeditor.material.png");
            _pathList.Add("icons/treeeditor.refresh.png");
            _pathList.Add("icons/treeeditor.trash.png");
            _pathList.Add("icons/treeeditor.wind on.png");
            _pathList.Add("icons/treeeditor.wind.png");
            _pathList.Add("icons/unityeditor.animationwindow.png");
            _pathList.Add("icons/unityeditor.asmainwindow.png");
            _pathList.Add("icons/unityeditor.consolewindow.png");
            _pathList.Add("icons/unityeditor.debuginspectorwindow.png");
            _pathList.Add("icons/unityeditor.finddependencies.png");
            _pathList.Add("icons/unityeditor.gameview.png");
            _pathList.Add("icons/unityeditor.graphs.animatorcontrollertool.png");
            _pathList.Add("icons/unityeditor.hierarchywindow.png");
            _pathList.Add("icons/unityeditor.inspectorwindow.png");
            _pathList.Add("icons/unityeditor.lookdevview.png");
            _pathList.Add("icons/unityeditor.profilerwindow.png");
            _pathList.Add("icons/unityeditor.scenehierarchywindow.png");
            _pathList.Add("icons/unityeditor.sceneview.png");
            _pathList.Add("icons/unityeditor.serverview.png");
            _pathList.Add("icons/unityeditor.versioncontrol.png");
            _pathList.Add("icons/unitylogo.png");
            _pathList.Add("icons/unitylogolarge.png");
            _pathList.Add("icons/uparrow.png");
            _pathList.Add("icons/vcs_add.png");
            _pathList.Add("icons/vcs_branch.png");
            _pathList.Add("icons/vcs_change.png");
            _pathList.Add("icons/vcs_check.png");
            _pathList.Add("icons/vcs_delete.png");
            _pathList.Add("icons/vcs_document.png");
            _pathList.Add("icons/vcs_edit.png");
            _pathList.Add("icons/vcs_incoming.png");
            _pathList.Add("icons/vcs_integrate.png");
            _pathList.Add("icons/vcs_local.png");
            _pathList.Add("icons/vcs_lock.png");
            _pathList.Add("icons/vcs_refresh.png");
            _pathList.Add("icons/vcs_sync.png");
            _pathList.Add("icons/vcs_unresolved.png");
            _pathList.Add("icons/vcs_update.png");
            _pathList.Add("icons/verticalsplit.png");
            _pathList.Add("icons/viewtoolmove on.png");
            _pathList.Add("icons/viewtoolmove.png");
            _pathList.Add("icons/viewtoolorbit on.png");
            _pathList.Add("icons/viewtoolorbit.png");
            _pathList.Add("icons/viewtoolzoom on.png");
            _pathList.Add("icons/viewtoolzoom.png");
            _pathList.Add("icons/visibilityoff.png");
            _pathList.Add("icons/visibilityon.png");
            _pathList.Add("icons/vumetertexturehorizontal.png");
            _pathList.Add("icons/vumetertexturevertical.png");
            _pathList.Add("icons/waitspin00.png");
            _pathList.Add("icons/waitspin01.png");
            _pathList.Add("icons/waitspin02.png");
            _pathList.Add("icons/waitspin03.png");
            _pathList.Add("icons/waitspin04.png");
            _pathList.Add("icons/waitspin05.png");
            _pathList.Add("icons/waitspin06.png");
            _pathList.Add("icons/waitspin07.png");
            _pathList.Add("icons/waitspin08.png");
            _pathList.Add("icons/waitspin09.png");
            _pathList.Add("icons/waitspin10.png");
            _pathList.Add("icons/waitspin11.png");
            _pathList.Add("icons/welcomescreen.asset");
            _pathList.Add("icons/winbtn_graph.png");
            _pathList.Add("icons/winbtn_graph_close_h.png");
            _pathList.Add("icons/winbtn_graph_max_h.png");
            _pathList.Add("icons/winbtn_graph_min_h.png");
            _pathList.Add("icons/winbtn_mac_close.png");
            _pathList.Add("icons/winbtn_mac_close_a.png");
            _pathList.Add("icons/winbtn_mac_close_h.png");
            _pathList.Add("icons/winbtn_mac_inact.png");
            _pathList.Add("icons/winbtn_mac_max.png");
            _pathList.Add("icons/winbtn_mac_max_a.png");
            _pathList.Add("icons/winbtn_mac_max_h.png");
            _pathList.Add("icons/winbtn_mac_min.png");
            _pathList.Add("icons/winbtn_mac_min_a.png");
            _pathList.Add("icons/winbtn_mac_min_h.png");
            _pathList.Add("icons/winbtn_win_close.png");
            _pathList.Add("icons/winbtn_win_close_a.png");
            _pathList.Add("icons/winbtn_win_close_h.png");
            _pathList.Add("icons/winbtn_win_max.png");
            _pathList.Add("icons/winbtn_win_max_a.png");
            _pathList.Add("icons/winbtn_win_max_h.png");
            _pathList.Add("icons/winbtn_win_min.png");
            _pathList.Add("icons/winbtn_win_min_a.png");
            _pathList.Add("icons/winbtn_win_min_h.png");
            _pathList.Add("icons/winbtn_win_rest.png");
            _pathList.Add("icons/winbtn_win_rest_a.png");
            _pathList.Add("icons/winbtn_win_rest_h.png");
        }
    }
}